name: among_us_profile_maker
description: Among us avatar maker

version: 1.4.3+11

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  path_provider: ^1.6.22
  smooth_page_indicator: ^0.2.0
  image_gallery_saver: ^1.6.1
  permission_handler: ^5.0.1+1
  esys_flutter_share: ^1.0.2
  firebase_core: ^0.5.0+1
  firebase_analytics: ^6.0.2
  firebase_admob: ^0.10.1
  firebase_auth: ^0.18.1+2
  firebase_storage: ^4.0.1
  cloud_firestore: ^0.14.1+3
  paginate_firestore: ^0.2.1
  audioplayers: ^0.16.2
  shared_preferences: ^0.5.12+4
  animations: ^1.1.2
  cached_network_image: ^2.3.3
  http: ^0.12.2
  store_redirect: ^1.0.2
  double_back_to_close: ^1.0.2+mit
  flushbar: ^1.10.4
  o_color_picker: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  fonts:
    - family: AmongUs
      fonts:
        - asset: assets/fonts/VCR_OSD_MONO_1.001.ttf

  uses-material-design: true
  assets:
    - images/
    - images/BG/
    - images/PLAYER/
    - images/BOTONES/
    - images/HATS/
    - images/OUTFITS/
    - images/PETS/
    - images/VOTE/
    - assets/effect/select.mp3
    - assets/locale/de.json
    - assets/locale/en.json
    - assets/locale/es.json
    - assets/locale/fr.json
    - assets/locale/id.json
    - assets/locale/it.json
    - assets/locale/pt.json
    - assets/locale/ru.json
    - assets/locale/vi.json
